# ===============================================
# Configuration Spring Boot
# ===============================================
spring:
  application:
    name: notification-service # Le nom de l'application

# ===============================================
# Configuration des propriétés personnalisées
# ===============================================

# Propriétés spécifiques à notre application, regroupées sous 'app'
app:
  # Configuration pour Google Cloud Pub/Sub
  pubsub:
    # Nom de la subscription que ce service doit écouter pour recevoir les messages.
    # C'est la configuration principale de ce microservice.
    subscription-name: envoi-notifications-sub